name: Enforce branch name for docs

on:
  create:
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Checking branch name: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" == documentation* && "$BRANCH_NAME" != docs/* ]]; then
            echo "❌ Branches relacionadas à documentação devem começar com 'docs/'"
            exit 1
          else
            echo "✅ Nome de branch válido"
          fi
